services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: douglas
      POSTGRES_PASSWORD: douglas

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
